SELECT 
T1.PRODUCT_ID, IFNULL(ROUND(SUM(T1.PRICE* T2.UNITS)/SUM(T2.UNITS),2),0) 
AS AVERAGE_PRICE FROM PRICES T1 LEFT JOIN UNITSSOLD T2
ON  T1.PRODUCT_ID = T2.PRODUCT_ID 
AND T2.PURCHASE_DATE BETWEEN T1.START_DATE AND T1.END_DATE
GROUP BY PRODUCT_ID;
